services:
  db:
    image: postgres:13.14-alpine3.19
    environment:
      POSTGRES_PASSWORD: "password"
    ports:
      - 5432:5432
    volumes:
        - postgres-data:/var/lib/postgresql/data
  calendarbot:
    #image: ghcr.io/teamsolidch/calendarbot:v0.0.1-pr-31
    image: calendarbot
    env_file: .env
    volumes:
      - ./service/:/service/
volumes:
  postgres-data:
