name: Test and validate

on:
  pull_request:

jobs:
  ci:
    name: 'CI'
    runs-on: 'ubuntu-latest'
    container: rust:1.79-bullseye
    steps:
      - uses: 'actions/checkout@v4'
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@v26
      - uses: cachix/cachix-action@v14
        with:
          name: devenv
      - name: 'Install libc6'
        run: 'sudo apt update && sudo apt install libc6'
      - name: 'Run tests'
        run: 'nix develop --impure --command bash -c "moon ci :test" #.'
      - name: 'Run lint'
        run: 'nix develop --impure --command bash -c "moon ci :lint" #.'
      - name: 'Run format'
        run: 'nix develop --impure --command bash -c "moon ci :format" #.'
