name: Test and validate

on:
  pull_request:

jobs:
  ci:
    name: 'CI'
    runs-on: 'ubuntu-24.04'
    steps:
      - uses: 'actions/checkout@v4'
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@v26
      - uses: cachix/cachix-action@v14
        with:
          name: devenv
      - name: "ldd version"
        run: 'ldd --version'
      - name: 'Run tests'
        run: 'nix develop --impure --accept-flake-config --command bash -c "moon ci :test" #.'
      - name: 'Run lint'
        run: 'nix develop --impure --accept-flake-config --command bash -c "moon ci :lint" #.'
      - name: 'Run format'
        run: 'nix develop --impure --accept-flake-config --command bash -c "moon ci :format" #.'
