name: Test and validate

on:
  pull_request:

jobs:
  ci:
    name: 'CI'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v4'
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@v26
      - uses: cachix/cachix-action@v14
        with:
          name: devenv
      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv
      - uses: HatsuneMiku3939/direnv-action@v1
      - uses: moonrepo/setup-toolchain@v0
        with:
          moon-version: '1.27.5' 
      - uses: moonrepo/setup-rust@v1
      - name: 'Run tests'
        run: 'moon ci :test'
      - name: 'Run lint'
        run: 'moon ci :lint'
      - name: 'Run format'
        run: 'moon ci :format'
