name: Test and validate

on:
  pull_request:

jobs:
  ci:
    name: 'CI'
    runs-on: 'ubuntu-latest'
    container: rust:1.79
    steps:
      - uses: 'actions/checkout@v4'
        with:
          fetch-depth: 0
      - name: Install nix
        run: | 
          mkdir -p /etc/nix/
          echo "build-users-group =" > /etc/nix/nix.conf
          sh <(curl --retry 5 --retry-connrefused -L "${INPUT_INSTALL_URL:-https://nixos.org/nix/install}") --no-channel-add --darwin-use-unencrypted-nix-store-volume --nix-extra-conf-file /tmp/nix.conf
      - uses: cachix/cachix-action@v14
        with:
          name: devenv
      - name: 'Install libc6'
        run: 'sudo apt update && sudo apt install libc6'
      - name: 'Run tests'
        run: 'nix develop --impure --command bash -c "moon ci :test" #.'
      - name: 'Run lint'
        run: 'nix develop --impure --command bash -c "moon ci :lint" #.'
      - name: 'Run format'
        run: 'nix develop --impure --command bash -c "moon ci :format" #.'
