name: Test and validate

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: 'CI'
    runs-on: 'ubuntu-24.04'
    steps:
      - uses: 'actions/checkout@v4'
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@v17
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v11
        with:
          name: yoyozbi-ci-cache
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: "Setup env"
        uses: JRMurr/direnv-nix-action@v4.1.0
        with:
          install-nix: "false"
          cache-store: "false"      
      - name: 'Run tests'
        run: 'moon ci :test'
        shell: bash
      - name: 'Run lint'
        run: 'moon ci :lint'
        shell: bash
      - name: 'Run format'
        run: 'moon ci :format'
        shell: bash
