name: Test and validate

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: 'CI'
    runs-on: 'ubuntu-24.04'
    steps:
      - uses: 'actions/checkout@v4'
        with:
          fetch-depth: 0
      - name: "Setup env"
        uses: JRMurr/direnv-nix-action@v4.1.0
      - name: 'Run tests'
        run: 'nix develop --impure --accept-flake-config --command bash -c "moon ci :test" #.'
        shell: bash
      - name: 'Run lint'
        run: 'nix develop --impure --accept-flake-config --command bash -c "moon ci :lint" #.'
        shell: bash
      - name: 'Run format'
        run: 'nix develop --impure --accept-flake-config --command bash -c "moon ci :format" #.'
        shell: bash
